[tasks.bpxe-js-wasm]
command = "wasm-pack"
args = ["build", "--release", "bpxe"]

[tasks.bpxe-js]
dependencies = ["bpxe-js-wasm"]
script = [
   "cp bpxe/pkg/bpxe_bg* bpxe/pkg/bpxe.js bpxe/pkg/bpxe.d.ts bpxe.js",
]

[tasks.js]
workspace = false
dependencies = ["bpxe-js"]
