name: Publish docs

on:
  push:
    branches:
    - master

jobs:
  publish:

    continue-on-error: true

    name: Publish ${{ matrix.branch }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        branch: ['master']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup - gcloud / gsutil
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        project_id: ${{ secrets.GCS_PROJECT }}
        export_default_credentials: true

    - name: Install stable Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Build docs
      run: |-
        cargo doc --all-features
        mkdir -p content
        mv target/doc/* content

    - name: Deploy
      run: |-
        gsutil -m rsync -R content gs://${{ secrets.GCS_DOCS_BUCKET }}/${{ matrix.branch }}
